In [1]:
#we have imported the necessary packages.
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import re
import matplotlib.pyplot as plt

# here we reading the true and fake datasets

In [2]:
df_fake=pd.read_csv("Fake.csv")
df_true=pd.read_csv("True.csv")

In [3]:
df_fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [4]:
df_true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [5]:
df_true.shape#checking the shape of true.csv file

(21417, 4)

# we have to add the target column

In [6]:
#from the dataset given there is no dependent column which means there is no target column so we adding the target column by naming it as class
df_fake['class']=0
df_true['class']=1

In [7]:
df_fake.head()

,title,text,subject,date,class
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [8]:
df_true.head()

,title,text,subject,date,class
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

# we are merging the both datasets now

In [9]:
#by using the concat method in pandas we are merging the real,fake dataframes.
df_merge=pd.concat([df_fake,df_true])

In [10]:
df_merge

,title,text,subject,date,class
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
...,...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

# Here we are importing stopwords from nltk package to remove unnecessary words which doesn't give much importance to the sentences

In [11]:
from nltk.corpus import stopwords

In [12]:
from nltk.stem.porter import PorterStemmer

In [13]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [14]:
stop_words=stopwords.words("english")

In [119]:
stop_words

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [16]:
port_stemmer=PorterStemmer()#calling the instance.

# The process of stemming entails creating morphological variations of a root or base word.Ex- If a phrase contains the word "eating," it changes into the root word "eat."

In [17]:
#Here we are using function for performing stemming to the columns like-title,test
def stemming(columns):
        stemmed_column=re.sub('[^a-zA-Z]',' ',columns)
        stemmed_column=stemmed_column.lower()
        stemmed_column=stemmed_column.split()
        stemmed_column=[port_stemmer.stem(word) for word in stemmed_column if not word in stop_words]
        stemmed_column=' '.join(stemmed_column)
        return stemmed_column

In [18]:
df_merge['title']=df_merge['title'].apply(stemming)
df_merge['text']=df_merge['text'].apply(stemming)

In [19]:
df_merge#after performing stemming the titleand text doesn't contain any stopwords and it contains only root words as we performed stemming

,title,text,subject,date,class
0,donald trump send embarrass new year eve messa...,donald trump wish american happi new year leav...,News,"December 31, 2017",0
1,drunk brag trump staffer start russian collus ...,hous intellig committe chairman devin nune go ...,News,"December 31, 2017",0
2,sheriff david clark becom internet joke threat...,friday reveal former milwauke sheriff david cl...,News,"December 30, 2017",0
3,trump obsess even obama name code websit imag,christma day donald trump announc would back w...,News,"December 29, 2017",0
4,pope franci call donald trump christma speech,pope franci use annual christma day messag reb...,News,"December 25, 2017",0
...,...,...,...,...,...
21412,fulli commit nato back new u approach afghanistan,brussel reuter nato alli tuesday welcom presid...,worldnews,"August 22, 2017",1
21413,lexisnexi withdrew two product chines market,london reuter lexisnexi provid legal regulator...,worldnews,"August 22, 2017",1
21414,minsk cultur hub becom author,minsk reuter shadow disus soviet era factori m...,worldnews,"August 22, 2017",1
21415,vatican upbeat possibl pope franci visit russia,moscow reuter vatican secretari state cardin p...,worldnews,"August 22, 2017",1
21416,indonesia buy billion worth russian jet,jakarta reuter indonesia buy sukhoi fighter je...,worldnews,"August 22, 2017",1

In [20]:
df_merge.drop('date',axis=1,inplace=True)#As there is no time-series analysis in this instance, we are dropping the date column.

In [21]:
df_merge

,title,text,subject,class
0,donald trump send embarrass new year eve messa...,donald trump wish american happi new year leav...,News,0
1,drunk brag trump staffer start russian collus ...,hous intellig committe chairman devin nune go ...,News,0
2,sheriff david clark becom internet joke threat...,friday reveal former milwauke sheriff david cl...,News,0
3,trump obsess even obama name code websit imag,christma day donald trump announc would back w...,News,0
4,pope franci call donald trump christma speech,pope franci use annual christma day messag reb...,News,0
...,...,...,...,...
21412,fulli commit nato back new u approach afghanistan,brussel reuter nato alli tuesday welcom presid...,worldnews,1
21413,lexisnexi withdrew two product chines market,london reuter lexisnexi provid legal regulator...,worldnews,1
21414,minsk cultur hub becom author,minsk reuter shadow disus soviet era factori m...,worldnews,1
21415,vatican upbeat possibl pope franci visit russia,moscow reuter vatican secretari state cardin p...,worldnews,1
21416,indonesia buy billion worth russian jet,jakarta reuter indonesia buy sukhoi fighter je...,worldnews,1

In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
label_encoder=LabelEncoder()

In [24]:
df_merge['subject']=label_encoder.fit_transform(df_merge['subject'])

In [25]:
df_merge

,title,text,subject,class
0,donald trump send embarrass new year eve messa...,donald trump wish american happi new year leav...,2,0
1,drunk brag trump staffer start russian collus ...,hous intellig committe chairman devin nune go ...,2,0
2,sheriff david clark becom internet joke threat...,friday reveal former milwauke sheriff david cl...,2,0
3,trump obsess even obama name code websit imag,christma day donald trump announc would back w...,2,0
4,pope franci call donald trump christma speech,pope franci use annual christma day messag reb...,2,0
...,...,...,...,...
21412,fulli commit nato back new u approach afghanistan,brussel reuter nato alli tuesday welcom presid...,7,1
21413,lexisnexi withdrew two product chines market,london reuter lexisnexi provid legal regulator...,7,1
21414,minsk cultur hub becom author,minsk reuter shadow disus soviet era factori m...,7,1
21415,vatican upbeat possibl pope franci visit russia,moscow reuter vatican secretari state cardin p...,7,1
21416,indonesia buy billion worth russian jet,jakarta reuter indonesia buy sukhoi fighter je...,7,1

# tfidfvectorizer is being used to translate the text into values for computer comprehension.

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [27]:
tfidf_vectorizer=TfidfVectorizer()

In [28]:
title=df_merge['title'].values
text=df_merge['text'].values

In [29]:
tfidf_vectorizer.fit(title)
title_vectorizer=tfidf_vectorizer.transform(title)

In [30]:
print(title_vectorizer)

  (0, 13104)	0.285897289994607
  (0, 12010)	0.11874831789619875
  (0, 10341)	0.35617541225037314
  (0, 7866)	0.2355330109368446
  (0, 7335)	0.3506307808204068
  (0, 3949)	0.46737756630771704
  (0, 3731)	0.36585763997365384
  (0, 3404)	0.27228169452981993
  (0, 3339)	0.4152733860823366
  (1, 12010)	0.11694584057077226
  (1, 11065)	0.33812970188225466
  (1, 11031)	0.4051439782731002
  (1, 9996)	0.2804126957355963
  (1, 5989)	0.31272476199815336
  (1, 3523)	0.45452116468198644
  (1, 2289)	0.411400998172019
  (1, 1414)	0.3944388479979502
  (2, 11717)	0.25191024945597357
  (2, 10472)	0.3091623085438117
  (2, 8836)	0.42473021917033454
  (2, 8601)	0.2337777620708223
  (2, 6194)	0.3180103625234714
  (2, 5960)	0.2946136857056743
  (2, 4067)	0.2910179557797341
  (2, 2881)	0.3373830961140794
  :	:
  (44893, 169)	0.38874140539823904
  (44894, 12974)	0.4973695579127087
  (44894, 12115)	0.27583857506484
  (44894, 9067)	0.38705675445904325
  (44894, 7114)	0.3409101873703228
  (44894, 6698)	0.5424796406224016
  (44894, 2037)	0.3409101873703228
  (44895, 7446)	0.5568454848207488
  (44895, 5588)	0.48556690854103346
  (44895, 2765)	0.43267354456761764
  (44895, 999)	0.3546452718896813
  (44895, 705)	0.3757235929805801
  (44896, 12645)	0.29712702873039365
  (44896, 12526)	0.4199333061122664
  (44896, 12426)	0.48936243918462813
  (44896, 9993)	0.23456390154256354
  (44896, 8911)	0.3367819326164344
  (44896, 8883)	0.35556911023109744
  (44896, 4531)	0.44835729517481493
  (44897, 13028)	0.46964736681440655
  (44897, 9996)	0.2952203713320425
  (44897, 6149)	0.44156676068379813
  (44897, 5839)	0.4468527862765209
  (44897, 1646)	0.41095526021267015
  (44897, 1130)	0.3587944265934589

In [31]:
tfidf_vectorizer.fit(text)
text_vectorizer=tfidf_vectorizer.transform(text)

In [32]:
print(text_vectorizer)

  (0, 87706)	0.26875959408413413
  (0, 87629)	0.08671473106081941
  (0, 86560)	0.0319484475591679
  (0, 86404)	0.02738199782160357
  (0, 86322)	0.018939929076279394
  (0, 86308)	0.027435211825342014
  (0, 86226)	0.034741716274265345
  (0, 85904)	0.18705126109096712
  (0, 85031)	0.02679012973879564
  (0, 85020)	0.0900274557950121
  (0, 85009)	0.061097164874937555
  (0, 84981)	0.0900274557950121
  (0, 84337)	0.037638234151918894
  (0, 83779)	0.021542604780305785
  (0, 82124)	0.03793570874484206
  (0, 80070)	0.022984844175275566
  (0, 80010)	0.11263483767246102
  (0, 79339)	0.12538799173630044
  (0, 77345)	0.020703604940166268
  (0, 76970)	0.0900274557950121
  (0, 76916)	0.05692362529071868
  (0, 76652)	0.02664916985705388
  (0, 76408)	0.045266663685727536
  (0, 75768)	0.02235804168683324
  (0, 75746)	0.08671473106081941
  :	:
  (44897, 16719)	0.048107765810988634
  (44897, 16663)	0.04303368840542599
  (44897, 15780)	0.05943548547818958
  (44897, 15715)	0.02931897924359416
  (44897, 15417)	0.0557532868235351
  (44897, 15274)	0.09423901937584366
  (44897, 15093)	0.0974566811864351
  (44897, 14843)	0.044703681178355374
  (44897, 14798)	0.2722609430500509
  (44897, 14447)	0.09000534475719536
  (44897, 11699)	0.13378968262222693
  (44897, 10781)	0.06207604588023359
  (44897, 10593)	0.0577951979181575
  (44897, 7678)	0.04860799246456748
  (44897, 7631)	0.07455817333047993
  (44897, 4950)	0.17798399918772265
  (44897, 4277)	0.07100889564082159
  (44897, 4275)	0.06505402640961297
  (44897, 2692)	0.04378386526688423
  (44897, 2623)	0.061929911183421546
  (44897, 2300)	0.025668324392092816
  (44897, 1480)	0.0500186680251168
  (44897, 1191)	0.05921714309050012
  (44897, 724)	0.05148980670553149
  (44897, 477)	0.08073110571054928

In [37]:
from sklearn.model_selection import train_test_split

In [104]:
x=text_vectorizer

In [105]:
y=df_merge["class"].values

# here we perform train_test_split.

In [106]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=40)

# To determine if the news is true or false, we are utilising the logistic regression approach on this dataset.

In [107]:
from sklearn.linear_model import LogisticRegression

In [108]:
log_reg=LogisticRegression()

In [109]:
log_reg.fit(x_train,y_train)

LogisticRegression()

In [110]:
xtrain_pred=log_reg.predict(x_train)

In [111]:
from sklearn.metrics import accuracy_score

In [112]:
training_data_accuracy=accuracy_score(xtrain_pred,y_train)

In [113]:
print("The accuracy of training data is:",training_data_accuracy)

The accuracy of training data is: 0.9905498281786942

In [114]:
xtest_pred=log_reg.predict(x_test)

In [115]:
testing_data_accuracy=accuracy_score(xtest_pred,y_test)

In [116]:
print("The accuracy of testing  data is:",testing_data_accuracy)

The accuracy of testing  data is: 0.9854491462509279

In [117]:
x_check=x_test[5]
pred=log_reg.predict(x_check)#checking.

In [118]:
if(pred[0]==0):
    print("The news is real")
else:
    print("The news is fake")

The news is fake

In [124]:
x_check1=x_test[17]
pred1=log_reg.predict(x_check1)

In [125]:
if(pred1[0]==0):
    print("The news is real")
else:
    print("The news is fake")

The news is real